README.md
ansible/playbooks/molecule/default_ec2/molecule.yml
ansible/playbooks/molecule/resources/ec2/create.yml
buildspec.yml

Fixed EC2 builds

---

bin/run-ansible.sh

Reverts shadow-robot/aurora#33

Revert "F#docker login"

---

ansible/playbooks/install_software.yml
ansible/roles/installation/terminator/defaults/main.yml
ansible/roles/installation/terminator/files/config
ansible/roles/installation/terminator/tasks/main.yml
ansible/roles/products/teleop/client/deploy/tasks/main.yml
ansible/roles/products/teleop/server/deploy/tasks/main.yml

added terminator

---

ansible/data/ansible/requirements.txt
ansible/data/molecule/requirements.txt

fixed cryptography version and added setuptools requirement

---

ansible/roles/products/common/validation/tasks/main.yml

Fix validation for ethercat_right/left_hand

Fix validation for ethercat_right/left_hand

---

bin/run-ansible.sh

Fix docker image builds

---

bin/run-ansible.sh

fix the check for ansible version check

fix the check for ansible version check

---

README.md
ansible/data/molecule/requirements.txt
ansible/inventory/local/group_vars/docker_deploy.yml
ansible/inventory/server_and_nuc/group_vars/control_machine.yml
ansible/inventory/server_and_nuc/group_vars/server.yml
ansible/inventory/teleop/group_vars/client.yml
ansible/inventory/teleop/group_vars/control_machine.yml
ansible/inventory/teleop/group_vars/server.yml
ansible/inventory/teleop/group_vars/simulation.yml
ansible/playbooks/molecule_docker/molecule/hand_e_empty_machine_docker/cleanup.yml
ansible/roles/docker/docker-image/meta/requirements.yml
ansible/roles/docker/docker-image/tasks/main.yml
ansible/roles/installation/aws-cli/files/requirements.txt
ansible/roles/installation/docker/tasks/main.yml
ansible/roles/installation/nvidia-docker/tasks/main.yml
ansible/roles/installation/nvidia-docker/tasks/nvidia-container-toolkit.yml
ansible/roles/products/common/docker-container/defaults/main.yml
ansible/roles/products/common/docker-container/meta/requirements.yml
ansible/roles/products/common/docker-container/tasks/create-container/no-setup-no-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/no-setup-with-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/nvidia-with-setup-with-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/with-setup-no-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/with-setup-with-terminator.yml
ansible/roles/products/common/docker-container/tasks/main.yml
bin/run-ansible.sh

use nvidia-container-toolkit rather than the deprecated nvidia-docker2

use nvidia-container-toolkit rather than the deprecated nvidia-docker2

---

bin/run-ansible.sh

correctly uninstall previous versions of ansible

correctly uninstall previous versions of ansible

---

docker/molecule/base/bionic/buildspec.yml
docker/molecule/base/xenial/buildspec.yml
docker/molecule/devel/bionic/buildspec.yml
docker/molecule/devel/xenial/buildspec.yml
docker/molecule/docker/bionic/Dockerfile
docker/molecule/docker/bionic/buildspec.yml
docker/molecule/docker/xenial/Dockerfile
docker/molecule/docker/xenial/buildspec.yml
docker/molecule/ec2/bionic/buildspec.yml
docker/molecule/ec2/xenial/buildspec.yml
docker/test/docker/bionic/Dockerfile
docker/test/docker/bionic/buildspec.yml
docker/test/docker/xenial/Dockerfile
docker/test/docker/xenial/buildspec.yml
docker/test/ubuntu/bionic/buildspec.yml
docker/test/ubuntu/xenial/buildspec.yml

set branch to master

---

ansible/roles/products/common/docker-container/defaults/main.yml

Allow dev sharing between host and docker.

Allow all dev

---

ansible/roles/products/hand-e/server/desktop-icons/defaults/main.yml
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual-arm-hand.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual.j2

Fix bimanual

---

ansible/roles/installation/vscode/tasks/main.yml

Src 6025 fix vscode

---

ansible/roles/products/teleop/server/desktop-icons/tasks/only-simulation.yml

Fixing conditions for teleop simulation icons (unimanual)

Fixing conditions for teleop simulation icons (unimanual)

---

ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-bimanual.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-left.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-right.j2

updating {{ glove }}

---

ansible/roles/products/teleop/server/desktop-icons/defaults/main.yml

Update argument for haptx side left mapping

Update argument for haptx side left mapping

---

ansible/roles/products/common/record-hand-data/tasks/main.yml

User story: https://shadowrobot.atlassian.net/browse/SRC-6466
Adding a cron job to repair active rosbags before sync. 

Adding script to repair active rosbags

---

ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-bimanual.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-left.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-right.j2

Adding temporary workaround until [SRC-6063](https://shadowrobot.atlassian.net/browse/SRC-6063) is fixed

adding sleeps with comment

---

ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-bimanual.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-left.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-right.j2

Reverts shadow-robot/aurora#369

Revert "SRC-6063 Wait for trajectory topic instead of sleeping"

---

ansible/roles/products/common/demo-icons/tasks/main.yml

Fixed an issue where an icon did not have the correct name value.

Fixed a issue where a icon has the wrong name.

---

ansible/roles/installation/steamvr/tasks/main.yml
ansible/roles/products/teleop/server/desktop-icons/defaults/main.yml

Reverts shadow-robot/aurora#386

reverting vive temporary 

---

ansible/roles/docker/docker-image/tasks/main.yml

Added a force condition based on the reinstall variable, if its true it will pull the latest image, if its false it will use the current image (but still pull if no image exists).

Src 6835 latest images get pulled

---

ansible/inventory/teleop/events_1

Adding new inventory to be used with equipment labelled as event_1 

Added new inventory in aurora for events

---

ansible/roles/products/teleop/server/desktop-icons/defaults/main.yml
ansible/roles/products/teleop/server/desktop-icons/tasks/real-robots.yml
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-bimanual-remote.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-left-remote.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-right-remote.j2

User Story: https://shadowrobot.atlassian.net/browse/SRC-6893
Adding icons for remote teleop based on aurora condition **remote_icons=true**. 

Adding icons for remote teleop (dev testing)

---

ansible/roles/products/common/docker-container/defaults/main.yml
ansible/roles/products/common/docker-container/tasks/reinstall.yml

Makes a copy of the customers response if aurora is run with reinstall = true (only copies response file if it exists).

Src 6822 implement licencing

---

ansible/roles/products/common/demo-icons/tasks/main.yml

fixing command as the command line doesn't like different ways of passing args

fixing rosrun command for demos

---

ansible/playbooks/docker_deploy.yml
ansible/roles/products/common/dolphin-icons/tasks/main.yml
ansible/roles/products/common/resources/templates/scripts/setup-hand.j2

A PR to make sure the hand_lite is set up correctly when running aurora.

Fix hand e light

---

ansible/roles/installation/steamvr/tasks/main.yml

Updated version of multiarch support as old debian got deleted.

Updated multiarch support version.

---

ansible/roles/installation/vscode/tasks/main.yml

Updating VSCode version from 1.35 to 1.65

Updating VSCode version from 1.35 to 1.65

---

ansible/data/ansible/requirements.txt
ansible/data/molecule/requirements.txt
ansible/roles/installation/aws-cli/files/requirements.txt
docker/molecule/base/bionic/buildspec.yml
docker/molecule/base/focal/buildspec.yml
docker/molecule/devel/bionic/buildspec.yml
docker/molecule/devel/focal/buildspec.yml
docker/molecule/docker/bionic/buildspec.yml
docker/molecule/docker/focal/buildspec.yml
docker/molecule/ec2/bionic/buildspec.yml
docker/molecule/ec2/focal/buildspec.yml
docker/test/docker/bionic/buildspec.yml
docker/test/docker/focal/buildspec.yml
docker/test/ubuntu/bionic/buildspec.yml
docker/test/ubuntu/focal/buildspec.yml

Updating some dependencies and fixing checks in aurora. There is an issue with how AWS is cloning aurora repo and this fixes it. It will be investigated later on how to do it properly but this allows us to do tests

Updating req

---

ansible/roles/docker/ecr/tasks/main.yml

Had to add default values for docker_deploy  and exited the playbook when a failure occurred.
- [] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).

Fix aws login

---

ansible/roles/products/common/cyberglove/templates/scripts/launch-cyberglove.j2
ansible/roles/products/common/resources/templates/scripts/command-script.j2
ansible/roles/products/common/resources/templates/scripts/modify-container.j2
ansible/roles/products/common/resources/templates/scripts/pull-pr-branches-and-catkin-make.j2
ansible/roles/products/common/resources/templates/scripts/roslaunch-script.j2
ansible/roles/products/common/resources/templates/scripts/rosrun-script.j2
ansible/roles/products/common/resources/templates/scripts/start-roscore.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual-arm-hand.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-command.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-interactive-terminal.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-command.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-interactive-terminal.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2

We were sourcing both base_deps and base at the same time, we only needed to source base though.

Removed base_dep sourcing from all isntances.

---

ansible/inventory/local/group_vars/docker_deploy.yml

Reverted docker_deploy default image to docker hub

---

bin/run-ansible.sh

This PR will ensure all correct ansible modules are removed.

Properly uninstall ansible if outdated version

---

ansible/inventory/teleop/group_vars/control_machine.yml
ansible/inventory/teleop/group_vars/server.yml
ansible/roles/products/teleop/server/desktop-icons/tasks/real-robots.yml
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-bimanual-8dof.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-left-8dof.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-right-8dof.j2

Made a default icon to launch everything using 8dof.

8dof default

---

ansible/roles/products/hand-e/server/desktop-icons/tasks/main.yml

Added GUI and control_loop advanced icons for hand+arm in server_and_nuc.

Added missing hand_arm icons

---

ansible/data/ansible/bionic/requirements.txt
ansible/data/ansible/requirements.txt
ansible/data/molecule/bionic/requirements.txt
ansible/data/molecule/requirements.txt
docker/molecule/base/focal/Dockerfile

Updated some requirements

---

ansible/data/molecule/bionic/requirements.txt
ansible/data/molecule/requirements.txt

Added boto for molecule images.

Added boto for molecule images

---

ansible/data/molecule/bionic/requirements.txt
ansible/data/molecule/requirements.txt

Added more testing reqs

---

ansible/roles/products/common/cyberglove/templates/scripts/launch-cyberglove.j2
ansible/roles/products/common/resources/templates/scripts/close-everything.j2
ansible/roles/products/common/resources/templates/scripts/command-script.j2
ansible/roles/products/common/resources/templates/scripts/roslaunch-script.j2
ansible/roles/products/common/resources/templates/scripts/rosrun-script.j2
ansible/roles/products/common/save-logs-icons/templates/scripts/save-latest-ros-logs.j2

Since we source elsewhere in the icons we are removing the ros_entrypoint.

Removed ros_entrypoint from Icon Scripts

---

ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual-arm-hand.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-command.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-bimanual.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-command.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc.j2

Fixing the logging output of nuc container.

Fixing logging output

---

ansible/roles/docker/ecr/tasks/main.yml

Added new api call to get hand+glove.

Added new api call to get hand+glove.

---

ansible/roles/products/hand-e/server/desktop-icons/tasks/main.yml

Fixed indent that was affecting server_and_nuc simulation icons.

Fixed indent that was affecting server_and_nuc simulation icons.

---

ansible/playbooks/docker_deploy.yml
ansible/playbooks/server_and_nuc_deploy.yml
ansible/playbooks/teleop_deploy.yml
ansible/roles/installation/dhcp/tasks/main.yml
ansible/roles/installation/nvidia-docker/tasks/nvidia-container-toolkit.yml
ansible/roles/installation/steamvr/tasks/main.yml
ansible/roles/products/common/arm-interfaces/tasks/main.yml
bin/run-ansible.sh

Jammying aurora

---

ansible/playbooks/server_and_nuc_deploy.yml
ansible/playbooks/teleop_deploy.yml
ansible/roles/installation/install_common_tools/tasks/main.yml
ansible/roles/installation/install_licence_tools/tasks/main.yml

Add yubikey requirements

---

ansible/roles/products/common/dolphin-icons/tasks/main.yml

Fixed quadruple bracket mistake.
- [] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).

Fixed quadruple bracket mistake.

---

ansible/playbooks/server_and_nuc_deploy.yml
ansible/roles/products/hand-e/server/deploy/tasks/main.yml

Fix icon name and glove calibration.

Fix icon name and glove calibration

---

ansible/roles/products/hand-e/server/deploy/tasks/main.yml

Moved the command to create the container after the shared volumes.

Moved the command to create the container after the shared volumes.

---

ansible/roles/installation/install_licence_tools/tasks/main.yml

Fixed yubikey repo not being added to new machines by adding become to the role.

Fixed yubikey repo not being added to new machines.

---

ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-shadow-glove-calibration.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-shadow-glove-calibration.j2

Removing running roscore and glove driver from calibration icon for hand & glove and teleop.

Removing running roscore and glove driver from calibration icon

---

ansible/roles/products/hand-e/server/desktop-icons/tasks/main.yml

Fix udev rules for hand+glove.

Fix udev rules for hand+glove

---

ansible/roles/products/common/resources/templates/scripts/close-everything.j2

Ignores Dolphin file manager in the pid selection

Stopped close everything from closing dolphin launcher

---

ansible/roles/products/hand-e/server/desktop-icons/tasks/main.yml

Added new links to hand_e and hand_lite documentation.

Added new links to hand_e and hand_lite documentation

---

README.md
docs/development.md

Updated the documentation for aurora and split some of the content.

Updated the documentation for aurora and split some of the content.

---

ansible/roles/products/teleop/server/desktop-icons/tasks/only-simulation.yml
ansible/roles/products/teleop/server/desktop-icons/tasks/real-robots.yml

Fixed bug with Icons pointing to old package.

Fixed bug with Icons pointing to old package.

---

ansible/roles/products/common/resources/templates/scripts/roslaunch-script.j2
ansible/roles/products/common/resources/templates/scripts/rosrun-script.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-command.j2
ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/start-docker-container-nuc-interactive-terminal.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-command.j2
ansible/roles/products/teleop/server/desktop-icons/templates/scripts/start-docker-container-nuc-interactive-terminal.j2

Added missing roslog format to NUC and GUI icons.

Added missing roslog format

---

ansible/roles/installation/nvidia-docker/tasks/main.yml

Added new feature to check the stability of Nivida During oneliners. First it makes sure you are using prime-select nvidia, the other feature is making sure nvidia is actually being used by querying nvidia-smi.

Added new feature to check the stability of Nivida During oneliners

---

ansible/roles/installation/nvidia-docker/tasks/main.yml
ansible/roles/products/common/demo-icons/tasks/main.yml
ansible/roles/products/common/local-hand-launch/defaults/main.yml
ansible/roles/products/common/local-hand-launch/tasks/main.yml
ansible/roles/products/hand-e/docker-deploy/desktop-icons/tasks/main.yml
ansible/roles/products/hand-e/server/desktop-icons/tasks/main.yml
ansible/roles/products/teleop/server/desktop-icons/tasks/real-robots.yml

Add missing demo icons and fix local launch. Also fixed a check when nvidia_smi isn't installed.

Add missing demo icons and fix local launch

---

ansible/roles/installation/steamvr/tasks/main.yml

Fixed issue with steamvr's image installation.

Fixed issue with steamvr's image installation

---

ansible/roles/installation/steamvr/tasks/main.yml
ansible/roles/products/common/documentation/tasks/main.yml
ansible/roles/products/common/dolphin-icons/tasks/main.yml
ansible/roles/products/common/resources/templates/desktop-icons/standard-icon-command.j2
ansible/roles/products/teleop/server/desktop-icons/tasks/steam-binding-icon.yml
bin/run-ansible.sh

Make it so Aurora automatically marks our desktop files to execute.

Make it so Aurora automatically marks our desktop files to execute

---

ansible/data/ansible/requirements.txt

Addresses cryptography/openssh dependency issue. Tested with:
`sudo pip uninstall $x` for x in this `requirements.txt` (on both server and nuc)
... and then re-running aurora. It's likely that you can manually install the wrong version of a package and re-break this dependency tree, so this probably isn't robust to different environments

F test no pinned cryptography

---

ansible/roles/products/common/save-logs-icons/templates/scripts/save-latest-ros-logs.j2

Changing ROS logs upload script to get any file that contains .bag.

Changing ROS logs to get any file that contains .bag

---

ansible/playbooks/install_python3.yml
ansible/roles/docker/ecr/tasks/main.yml

e.g:
X509_V_FLAG_NOTIFY_POLICY
X509_V_FLAG_CB_ISSUER_CHECK

F #src 7364 expand openssl error fix

---

ansible/roles/products/common/arm-interfaces/tasks/bionic.yml

cast arm interface name to lowercase

---

ansible/roles/docker/ecr/tasks/main.yml

Hopetully this one does it (follow on from https://github.com/shadow-robot/aurora/pull/583) - tested with toy example
Inspired by https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#stderr

B#pd 38 maybe fix illusive unreproducable error again

---

ansible/roles/docker/ecr/tasks/main.yml
ansible/roles/products/common/arm-interfaces/tasks/bionic.yml

update release branch with master release fixes 

---

ansible/roles/products/common/docker-container/tasks/reinstall.yml

remove sudo from .ssh dir

---

ansible/roles/products/common/documentation/tasks/main.yml

same as pull 592 but for release

same as pull 592 but for release

---

ansible/roles/docker/ecr/tasks/main.yml

Add new API call to access new ECR registry

---

ansible/inventory/local/docker_deploy
ansible/playbooks/install_python3.yml
ansible/playbooks/server_and_nuc_deploy.yml
ansible/playbooks/teleop_deploy.yml
ansible/roles/docker/docker-image/tasks/main.yml
ansible/roles/installation/conda_deploy/tasks/main.yml
ansible/roles/products/common/docker-container/tasks/create-container/no-setup-no-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/no-setup-with-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/nvidia-with-setup-with-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/with-setup-no-terminator.yml
ansible/roles/products/common/docker-container/tasks/create-container/with-setup-with-terminator.yml
bin/conda_utils.sh
bin/run-ansible.sh

- Fix "bug?" where single-machine deployments didnt' have ansible_control_node set, so would not use conda packages. 
- Split conda deployment stuff into new file so it can be called from an ansible role
- add ansible role to deploy conda onto the nuc, so that the nuc can use frozen conda pip packages

B debugging docker api http 2

---

ansible/roles/installation/conda_deploy/tasks/main.yml

Update url after merge

---

docker/molecule/docker/bionic/buildspec.yml
docker/molecule/docker/focal/buildspec.yml
docker/test/docker/bionic/buildspec.yml
docker/test/docker/focal/buildspec.yml

testing for null, no solution yet, just debugging

---

docker/molecule/docker/bionic/buildspec.yml
docker/molecule/docker/focal/buildspec.yml
docker/molecule/docker/jammy/buildspec.yml
docker/test/docker/bionic/buildspec.yml
docker/test/docker/focal/buildspec.yml
docker/test/docker/jammy/buildspec.yml

authenticate to increase rate limit from 50 per hour to ~5k

B add GitHub rest api auth

---

bin/conda_utils.sh
bin/run-ansible.sh

ok this one finally actually seems to hopefully isolate the environments

B isolate conda feb 2025

---

ansible/roles/products/common/docker-container/tasks/modify-container.yml

should have a reduced scope, shouldn't persist from other task calls

---

ansible/roles/installation/conda_deploy/tasks/main.yml

Try making NUC conda python env more like server

---

README.md

add conda description to readme
